apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: dvsr1411/flaskapp:v1
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "mysqldb"
        - name: MYSQL_DATABASE
          value: "mydb"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "Sathwik123"
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskapp
